server:
  port: 80
  session:
    timeout: 3600  #以秒为单位

spring:
    datasource:
        name: test
        url: jdbc:mysql://rm-wz9ntbz4289l3iec0io.mysql.rds.aliyuncs.com:3306/hello?useSSL=false&characterEncoding=utf8
        username: root
        password: Hyok@3603
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp

    cache:
      ehcache:
        config: classpath*:ehcache/ehcache.xml

mybatis:
  mapper-locations: classpath*:mappers/*/*.xml
  type-aliases-package: com.harry.entity.*

#pagehelper分页插件
  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql